"""
Figure S1: stochastic release-recapture lattice consistency check.

Purpose
-------
Test whether elementary two-site binding plus local release/recapture generates
an occupancy-transport window whose concentration dependence tracks the
measured coexistence of source-capable and acceptor-capable site states.

Important scope
---------------
The product form is not imposed in the microscopic simulation. Site occupancies
are generated by elementary R0 <-> RB <-> RAB kinetics under clamped free cAMP.
The transport observable D_occ is estimated independently from successful
release-recapture jump statistics, whereas the product is computed afterward
from time-averaged state fractions.

This is a microscopic plausibility/closure check, not a derivation of the 1D PDE
or a calibration of D_relay,0.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# Parameters
# -----------------------------
KB = 0.1       # uM, effective CNB-B loading threshold
KA = 1.0       # uM, effective CNB-A vacancy threshold
k_off_B = 10.0  # s^-1
k_on_B = k_off_B / KB  # uM^-1 s^-1
k_on_A = 10.0          # uM^-1 s^-1
k_off_A = k_on_A * KA  # s^-1

N_sites = 180
spacing_um = 0.10
capture_radius_sites = 6
capture_lambda_sites = 2.0

p_recapture_organized = 0.35
p_recapture_unorganized = 0.03

n_burn_events = 1500
n_collect_events = 8000
n_reps = 3
seed = 71

# Dense sampling around sqrt(KA KB), plus broad logarithmic range.
cmax_theory = np.sqrt(KA * KB)
c_log = np.logspace(-3, 1.2, 30)
c_peak = np.logspace(np.log10(0.08), np.log10(0.8), 8)
c_values = np.unique(np.round(np.concatenate([c_log, c_peak]), 12))

outdir = Path(__file__).resolve().parent / "outputs"
outdir.mkdir(parents=True, exist_ok=True)

# Distance kernel for recapture. Self-recapture is allowed but contributes
# zero displacement to D_occ.
offsets = np.arange(-capture_radius_sites, capture_radius_sites + 1)
weights = np.exp(-np.abs(offsets) / capture_lambda_sites)
weights = weights / weights.sum()


def initial_state(c, rng):
    """Sample sequential two-site equilibrium only for initialization."""
    w0 = 1.0
    w1 = c / KB
    w2 = (c / KB) * (c / KA)
    probs = np.array([w0, w1, w2], dtype=float)
    probs /= probs.sum()
    return rng.choice(np.array([0, 1, 2], dtype=np.int8), size=N_sites, p=probs)


def choose_site_with_state(state, state_value, rng):
    idx = np.flatnonzero(state == state_value)
    if idx.size == 0:
        return None
    return int(idx[rng.integers(idx.size)])


def simulate_one(c, p_recapture, rng):
    state = initial_state(c, rng)

    collect_time = 0.0
    weighted = {
        "rho_R0": 0.0,
        "rho_RB": 0.0,
        "rho_RAB": 0.0,
        "rho_B_occupied": 0.0,
        "rho_A_vacant": 0.0,
        "product_instantaneous": 0.0,
    }
    disp2_sum = 0.0
    successful_capture = 0
    attempted_release = 0

    total_events = n_burn_events + n_collect_events
    for ev in range(total_events):
        collecting = ev >= n_burn_events

        n0 = int(np.count_nonzero(state == 0))
        n1 = int(np.count_nonzero(state == 1))
        n2 = N_sites - n0 - n1

        rates = np.array([
            n0 * k_on_B * c,   # R0 -> RB
            n1 * k_off_B,      # RB -> R0, release B-bound cAMP
            n1 * k_on_A * c,   # RB -> RAB
            n2 * k_off_A,      # RAB -> RB, release A-bound cAMP
        ], dtype=float)
        rtot = rates.sum()
        if rtot <= 0:
            break

        dt = rng.exponential(1.0 / rtot)

        if collecting:
            collect_time += dt
            rho0 = n0 / N_sites
            rho1 = n1 / N_sites
            rho2 = n2 / N_sites
            rho_bocc = (n1 + n2) / N_sites
            rho_avac = (n0 + n1) / N_sites
            weighted["rho_R0"] += rho0 * dt
            weighted["rho_RB"] += rho1 * dt
            weighted["rho_RAB"] += rho2 * dt
            weighted["rho_B_occupied"] += rho_bocc * dt
            weighted["rho_A_vacant"] += rho_avac * dt
            weighted["product_instantaneous"] += (rho_bocc * rho_avac) * dt

        event_type = int(np.searchsorted(np.cumsum(rates), rng.random() * rtot, side="right"))
        released = False
        source = None

        if event_type == 0:
            i = choose_site_with_state(state, 0, rng)
            if i is not None:
                state[i] = 1
        elif event_type == 1:
            i = choose_site_with_state(state, 1, rng)
            if i is not None:
                state[i] = 0
                released = True
                source = i
        elif event_type == 2:
            i = choose_site_with_state(state, 1, rng)
            if i is not None:
                state[i] = 2
        else:
            i = choose_site_with_state(state, 2, rng)
            if i is not None:
                state[i] = 1
                released = True
                source = i

        if released and source is not None:
            if collecting:
                attempted_release += 1
            if rng.random() < p_recapture:
                offset = int(rng.choice(offsets, p=weights))
                target = (source + offset) % N_sites
                if state[target] < 2:
                    state[target] += 1
                    if collecting:
                        successful_capture += 1
                        raw = abs(target - source)
                        dist_sites = min(raw, N_sites - raw)
                        disp2_sum += (dist_sites * spacing_um) ** 2

    if collect_time <= 0:
        raise RuntimeError("No collection time accumulated")

    out = {k: v / collect_time for k, v in weighted.items()}
    # Independent mobility estimate from jump statistics.
    # Units are um^2/s per lattice site; only concentration dependence is used.
    out["D_occ_um2_s"] = disp2_sum / (2.0 * collect_time * N_sites)
    out["product_means"] = out["rho_B_occupied"] * out["rho_A_vacant"]
    out["capture_success_fraction"] = successful_capture / attempted_release if attempted_release > 0 else np.nan
    out["attempted_release"] = attempted_release
    out["successful_capture"] = successful_capture
    out["collect_time_s"] = collect_time
    out["c_uM"] = c
    out["p_recapture"] = p_recapture
    return out


def run_condition(label, p_recapture):
    rows = []
    label_seed = seed + (0 if label == "organized" else 100000)
    for ci, c in enumerate(c_values):
        for rep in range(n_reps):
            rng = np.random.default_rng(label_seed + 1000 * ci + rep)
            out = simulate_one(float(c), p_recapture, rng)
            out["organization"] = label
            out["replicate"] = rep
            rows.append(out)
        print(f"{label:11s} c={c:8.4g} done")
    return pd.DataFrame(rows)


def summarize(df):
    numeric = [
        "rho_R0", "rho_RB", "rho_RAB", "rho_B_occupied", "rho_A_vacant",
        "product_instantaneous", "product_means", "D_occ_um2_s",
        "capture_success_fraction", "attempted_release", "successful_capture",
        "collect_time_s", "p_recapture",
    ]
    grouped = df.groupby(["organization", "c_uM"], as_index=False)
    mean = grouped[numeric].mean()
    sem = grouped[numeric].sem().add_suffix("_sem")
    sem = pd.concat([grouped.size()[["organization", "c_uM"]], sem.reset_index(drop=True)], axis=1)
    return mean.merge(sem, on=["organization", "c_uM"], how="left")


print("Running organized lattice simulation...")
df_org = run_condition("organized", p_recapture_organized)
print("Running sparse/unorganized lattice simulation...")
df_unorg = run_condition("unorganized", p_recapture_unorganized)
df_raw = pd.concat([df_org, df_unorg], ignore_index=True)
df_summary = summarize(df_raw)

raw_csv = outdir / "FigS1_lattice_release_recapture_raw.csv"
summary_csv = outdir / "FigS1_lattice_release_recapture_summary.csv"
df_raw.to_csv(raw_csv, index=False)
df_summary.to_csv(summary_csv, index=False)

# -----------------------------
# Plot figure
# -----------------------------
plt.rcParams.update({
    "font.size": 8,
    "axes.titlesize": 9,
    "axes.labelsize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "legend.fontsize": 7,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})

org = df_summary[df_summary["organization"] == "organized"].copy()
unorg = df_summary[df_summary["organization"] == "unorganized"].copy()

xprod = org["product_means"].to_numpy()
yD = org["D_occ_um2_s"].to_numpy()
# Single scale factor fitted through the origin, not by matching the peak.
scale_fit = float(np.dot(xprod, yD) / np.dot(xprod, xprod))
org["product_scaled"] = org["product_means"] * scale_fit
pred = org["product_scaled"].to_numpy()
r2 = float(1.0 - np.sum((yD - pred) ** 2) / np.sum((yD - yD.mean()) ** 2))

# Peak location estimate from measured D_occ
peak_idx = int(np.argmax(org["D_occ_um2_s"].to_numpy()))
peak_c = float(org.iloc[peak_idx]["c_uM"])

fig, axes = plt.subplots(2, 2, figsize=(7.4, 6.2))
axes = axes.ravel()

# Panel A
ax = axes[0]
ax.plot(org["c_uM"], org["rho_B_occupied"], lw=2.0, label="B-occupied source-capable fraction")
ax.plot(org["c_uM"], org["rho_A_vacant"], lw=2.0, label="A-vacant acceptor-capable fraction")
ax.plot(org["c_uM"], org["product_means"], lw=2.3, ls="--", label="Measured product")
ax.axvline(cmax_theory, lw=1.0, ls=":")
ax.set_xscale("log")
ax.set_ylim(0, 1.05)
ax.set_xlabel("Clamped free cAMP (uM)")
ax.set_ylabel("Measured fraction")
ax.set_title("A. Elementary occupancy states", loc="left", fontweight="bold")
ax.grid(alpha=0.25)
ax.legend(frameon=True, loc="best")

# Panel B
ax = axes[1]
ax.errorbar(org["c_uM"], org["D_occ_um2_s"], yerr=org["D_occ_um2_s_sem"],
            lw=2.2, marker="o", ms=3.0, capsize=2, label=r"Measured $D_{occ}$")
ax.plot(org["c_uM"], org["product_scaled"], lw=2.0, ls="--", label="Measured product, one-scale fit")
ax.axvline(cmax_theory, lw=1.0, ls=":", label=r"$\sqrt{K_AK_B}$")
ax.axvline(peak_c, lw=0.9, ls="--", alpha=0.55, label="measured peak")
ax.set_xscale("log")
ax.set_xlabel("Clamped free cAMP (uM)")
ax.set_ylabel(r"Occupancy transport (um$^2$ s$^{-1}$)")
ax.set_title("B. Product-like transport window emerges", loc="left", fontweight="bold")
ax.grid(alpha=0.25)
ax.legend(frameon=True, loc="best")
ax.text(0.03, 0.06, rf"one-scale fit, $R^2={r2:.3f}$", transform=ax.transAxes,
        bbox=dict(facecolor="white", edgecolor="0.75", alpha=0.9), fontsize=7)

# Panel C
ax = axes[2]
ax.errorbar(org["c_uM"], org["D_occ_um2_s"], yerr=org["D_occ_um2_s_sem"],
            lw=2.2, marker="o", ms=3.0, capsize=2, label="organized recapture")
ax.errorbar(unorg["c_uM"], unorg["D_occ_um2_s"], yerr=unorg["D_occ_um2_s_sem"],
            lw=2.2, marker="o", ms=3.0, capsize=2, ls="--", label="sparse/unorganized recapture")
ax.axvline(cmax_theory, lw=1.0, ls=":")
ax.set_xscale("log")
ax.set_xlabel("Clamped free cAMP (uM)")
ax.set_ylabel(r"Measured $D_{occ}$ (um$^2$ s$^{-1}$)")
ax.set_title("C. Organization controls productive recapture", loc="left", fontweight="bold")
ax.grid(alpha=0.25)
ax.legend(frameon=True, loc="best")

# Panel D
ax = axes[3]
ax.errorbar(org["product_means"], org["D_occ_um2_s"], xerr=org["product_means_sem"],
            yerr=org["D_occ_um2_s_sem"], fmt="o", ms=4.0, capsize=2, label="organized lattice")
xx = np.linspace(0, org["product_means"].max() * 1.05, 100)
ax.plot(xx, scale_fit * xx, lw=1.8, ls="--", label="one-scale product fit")
ax.set_xlabel("Measured source fraction x acceptor fraction")
ax.set_ylabel(r"Measured $D_{occ}$ (um$^2$ s$^{-1}$)")
ax.set_title("D. Transport tracks measured state coexistence", loc="left", fontweight="bold")
ax.grid(alpha=0.25)
ax.legend(frameon=True, loc="best")

fig.tight_layout()
fig_png = outdir / "FigS1_lattice_release_recapture.png"
fig_pdf = outdir / "FigS1_lattice_release_recapture.pdf"
fig.savefig(fig_png, dpi=300, bbox_inches="tight")
fig.savefig(fig_pdf, dpi=300, bbox_inches="tight")

summary_path = outdir / "FigS1_lattice_parameter_summary.txt"
with open(summary_path, "w", encoding="utf-8") as f:
    f.write("Figure S1 lattice release-recapture parameter summary\n")
    f.write("========================================================\n\n")
    f.write("Purpose: microscopic closure check for product-like occupancy transport.\n")
    f.write("D_occ is estimated from successful release-recapture jump displacement variance.\n")
    f.write("The product term is computed independently from time-averaged occupancy fractions.\n")
    f.write("No analytic donor/acceptor availability function is imposed in the KMC.\n\n")
    f.write(f"K_B = {KB} uM; K_A = {KA} uM; sqrt(K_A K_B) = {cmax_theory:.4f} uM\n")
    f.write(f"Measured D_occ peak = {peak_c:.4f} uM\n")
    f.write(f"k_on_B = {k_on_B} uM^-1 s^-1; k_off_B = {k_off_B} s^-1\n")
    f.write(f"k_on_A = {k_on_A} uM^-1 s^-1; k_off_A = {k_off_A} s^-1\n")
    f.write(f"N_sites = {N_sites}; spacing = {spacing_um} um\n")
    f.write(f"Capture radius = +/-{capture_radius_sites} sites; kernel lambda = {capture_lambda_sites} sites\n")
    f.write(f"Organized p_recapture = {p_recapture_organized}\n")
    f.write(f"Sparse/unorganized p_recapture = {p_recapture_unorganized}\n")
    f.write(f"Replicates per concentration = {n_reps}\n")
    f.write(f"Burn-in events per replicate = {n_burn_events}\n")
    f.write(f"Collection events per replicate = {n_collect_events}\n")
    f.write(f"cAMP range = {c_values.min():.4g} to {c_values.max():.4g} uM\n")
    f.write(f"One-scale product fit slope = {scale_fit:.6g} um^2 s^-1\n")
    f.write(f"One-scale product comparison R^2 = {r2:.6f}\n")
    f.write("Scope: supports mean-field factorization of release-recapture mobility in the tested fast-exchange, local-capture regime; does not derive the continuum PDE or calibrate D_relay,0.\n")

print("Saved:")
print(fig_png)
print(fig_pdf)
print(summary_csv)
print(raw_csv)
print(summary_path)
